name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  card_swiper: ^3.0.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.9
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^13.0.1
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app-icon-2.png"
  min_sdk_android:  

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/